variables:
  AWS_ACCESS_KEY_ID: "$CI_ONLY_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "$CI_ONLY_AWS_SECRET_ACCESS_KEY"
  TF_VAR_DO_DOCKER_CA_CERT: $DO_DOCKER_CA_CERT
  TF_VAR_DO_DOCKER_CLIENT_CERT: $DO_DOCKER_CLIENT_CERT
  TF_VAR_DO_DOCKER_CLIENT_KEY: $DO_DOCKER_CLIENT_KEY

stages:
  - install
  - build
  - deploy

Install:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

Install:Deploy:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci --production
  artifacts:
    paths:
      - node_modules/

Test:
  stage: build
  image: node:lts-alpine
  script:
    - npm start lint
  dependencies:
    - Install

Build:
  stage: build
  image: node:lts-alpine
  script:
    - npm start build
  dependencies:
    - Install
  artifacts:
    paths:
      - dist/

.deploy_template: &deploy
  stage: deploy
  image:
    name: hashicorp/terraform:light
    entrypoint: [""]
  script:
    - terraform init
    - terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
    - terraform apply -auto-approve

Deploy to Alpha:
  <<: *deploy
  variables:
    ENVIRONMENT: alpha
  environment:
    name: alpha
    url: https://alpha.salte.ci
  only:
    - alpha

Deploy to Live:
  <<: *deploy
  variables:
    ENVIRONMENT: live
  environment:
    name: live
    url: https://salte.ci
  only:
    - live
