variables:
  AWS_ACCESS_KEY_ID: "$CI_ONLY_AWS_ACCESS_KEY"
  AWS_SECRET_ACCESS_KEY: "$CI_ONLY_AWS_SECRET_ACCESS_KEY"
  TF_VAR_DO_DOCKER_CA_CERT: $DO_DOCKER_CA_CERT
  TF_VAR_DO_DOCKER_CLIENT_CERT: $DO_DOCKER_CLIENT_CERT
  TF_VAR_DO_DOCKER_CLIENT_KEY: $DO_DOCKER_CLIENT_KEY

stages:
  - install
  - build
  - publish
  - deploy

Install:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci
  artifacts:
    paths:
      - node_modules/

Install:Deploy:
  stage: install
  image: node:lts-alpine
  cache:
    paths:
      - .npm/
  script:
    - npm ci --production
  artifacts:
    paths:
      - node_modules/

Test:
  stage: build
  image: node:lts-alpine
  script:
    - npm start lint
  dependencies:
    - Install

Build:
  stage: build
  image: node:lts-alpine
  script:
    - npm start build
  dependencies:
    - Install
  artifacts:
    paths:
      - dist/

Publish Image:
  stage: publish
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
    - docker build -t "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}" .
    - docker push "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
    - docker logout ${CI_REGISTRY}
  dependencies:
    - Build
  only:
    - live
    - alpha

.deploy_template: &deploy
  stage: deploy
  image:
    name: hashicorp/terraform:0.11.14
    entrypoint: [""]
  script:
    - terraform init
    - terraform workspace select $ENVIRONMENT || terraform workspace new $ENVIRONMENT
    - terraform apply -auto-approve

Deploy to Alpha:
  <<: *deploy
  variables:
    ENVIRONMENT: alpha
    TF_VAR_REGISTRY: "$CI_REGISTRY"
    TF_VAR_REGISTRY_USER: "$CI_REGISTRY_USER"
    TF_VAR_REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
    TF_VAR_IMAGE: "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}"
  environment:
    name: alpha
    url: https://alpha.salte.ci
  only:
    - alpha

Deploy to Live:
  <<: *deploy
  variables:
    ENVIRONMENT: live
    # TODO: Change this to Docker Hub Once we Go Live...
    TF_VAR_REGISTRY: "$CI_REGISTRY"
    TF_VAR_REGISTRY_USER: "$CI_REGISTRY_USER"
    TF_VAR_REGISTRY_PASSWORD: "$CI_REGISTRY_PASSWORD"
  environment:
    name: live
    url: https://salte.ci
  only:
    - live
